/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentPayoutsRouteImport } from './routes/payment.payouts'
import { Route as PaymentDashboardRouteImport } from './routes/payment.dashboard'
import { Route as CoachProgramsRouteImport } from './routes/coach.programs'
import { Route as CoachLibraryRouteImport } from './routes/coach.library'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as CoachDashboardRouteImport } from './routes/coach.dashboard'
import { Route as CoachChatRouteImport } from './routes/coach.chat'
import { Route as CoachAccessCodesRouteImport } from './routes/coach.access-codes'
import { Route as ClientWorkoutHistoryRouteImport } from './routes/client.workout-history'
import { Route as ClientProgressPicturesRouteImport } from './routes/client.progress-pictures'
import { Route as ClientProgramRouteImport } from './routes/client.program'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as ClientChatRouteImport } from './routes/client.chat'
import { Route as CoachProgramsIndexRouteImport } from './routes/coach.programs.index'
import { Route as CoachLibraryIndexRouteImport } from './routes/coach.library.index'
import { Route as CoachChatIndexRouteImport } from './routes/coach.chat.index'
import { Route as ClientProgressPicturesIndexRouteImport } from './routes/client.progress-pictures.index'
import { Route as ClientProgramIndexRouteImport } from './routes/client.program.index'
import { Route as CoachProgramsProgramIdRouteImport } from './routes/coach.programs.$programId'
import { Route as CoachLibraryWorkoutsRouteImport } from './routes/coach.library.workouts'
import { Route as CoachLibraryExercisesRouteImport } from './routes/coach.library.exercises'
import { Route as CoachClientsClientIdRouteImport } from './routes/coach.clients.$clientId'
import { Route as CoachChatClientIdRouteImport } from './routes/coach.chat.$clientId'
import { Route as ClientProgressPicturesBatchIdRouteImport } from './routes/client.progress-pictures.$batchId'
import { Route as CoachProgramsProgramIdIndexRouteImport } from './routes/coach.programs.$programId.index'
import { Route as CoachLibraryWorkoutsIndexRouteImport } from './routes/coach.library.workouts.index'
import { Route as CoachLibraryWorkoutsWorkoutIdRouteImport } from './routes/coach.library.workouts.$workoutId'
import { Route as ClientProgramWorkoutsWorkoutIdRouteImport } from './routes/client.program.workouts.$workoutId'
import { Route as CoachLibraryWorkoutsWorkoutIdIndexRouteImport } from './routes/coach.library.workouts.$workoutId.index'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId'
import { Route as CoachLibraryWorkoutsWorkoutIdPreviewRouteImport } from './routes/coach.library.workouts.$workoutId.preview'
import { Route as ClientProgramsProgramIdWorkoutsWorkoutIdRouteImport } from './routes/client.programs.$programId.workouts.$workoutId'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdIndexRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId.index'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId.preview'

const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPayoutsRoute = PaymentPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => PaymentRoute,
} as any)
const PaymentDashboardRoute = PaymentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PaymentRoute,
} as any)
const CoachProgramsRoute = CoachProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => CoachRoute,
} as any)
const CoachLibraryRoute = CoachLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachRoute,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CoachRoute,
} as any)
const CoachChatRoute = CoachChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAccessCodesRoute = CoachAccessCodesRouteImport.update({
  id: '/access-codes',
  path: '/access-codes',
  getParentRoute: () => CoachRoute,
} as any)
const ClientWorkoutHistoryRoute = ClientWorkoutHistoryRouteImport.update({
  id: '/workout-history',
  path: '/workout-history',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProgressPicturesRoute = ClientProgressPicturesRouteImport.update({
  id: '/progress-pictures',
  path: '/progress-pictures',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProgramRoute = ClientProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientChatRoute = ClientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ClientRoute,
} as any)
const CoachProgramsIndexRoute = CoachProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachProgramsRoute,
} as any)
const CoachLibraryIndexRoute = CoachLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachLibraryRoute,
} as any)
const CoachChatIndexRoute = CoachChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachChatRoute,
} as any)
const ClientProgressPicturesIndexRoute =
  ClientProgressPicturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientProgressPicturesRoute,
  } as any)
const ClientProgramIndexRoute = ClientProgramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientProgramRoute,
} as any)
const CoachProgramsProgramIdRoute = CoachProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => CoachProgramsRoute,
} as any)
const CoachLibraryWorkoutsRoute = CoachLibraryWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => CoachLibraryRoute,
} as any)
const CoachLibraryExercisesRoute = CoachLibraryExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachLibraryRoute,
} as any)
const CoachClientsClientIdRoute = CoachClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachChatClientIdRoute = CoachChatClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CoachChatRoute,
} as any)
const ClientProgressPicturesBatchIdRoute =
  ClientProgressPicturesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => ClientProgressPicturesRoute,
  } as any)
const CoachProgramsProgramIdIndexRoute =
  CoachProgramsProgramIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachProgramsProgramIdRoute,
  } as any)
const CoachLibraryWorkoutsIndexRoute =
  CoachLibraryWorkoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachLibraryWorkoutsRoute,
  } as any)
const CoachLibraryWorkoutsWorkoutIdRoute =
  CoachLibraryWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => CoachLibraryWorkoutsRoute,
  } as any)
const ClientProgramWorkoutsWorkoutIdRoute =
  ClientProgramWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => ClientProgramRoute,
  } as any)
const CoachLibraryWorkoutsWorkoutIdIndexRoute =
  CoachLibraryWorkoutsWorkoutIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachLibraryWorkoutsWorkoutIdRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => CoachProgramsProgramIdRoute,
  } as any)
const CoachLibraryWorkoutsWorkoutIdPreviewRoute =
  CoachLibraryWorkoutsWorkoutIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => CoachLibraryWorkoutsWorkoutIdRoute,
  } as any)
const ClientProgramsProgramIdWorkoutsWorkoutIdRoute =
  ClientProgramsProgramIdWorkoutsWorkoutIdRouteImport.update({
    id: '/programs/$programId/workouts/$workoutId',
    path: '/programs/$programId/workouts/$workoutId',
    getParentRoute: () => ClientRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachProgramsProgramIdWorkoutsWorkoutIdRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => CoachProgramsProgramIdWorkoutsWorkoutIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/client': typeof ClientRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRouteWithChildren
  '/client/chat': typeof ClientChatRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/program': typeof ClientProgramRouteWithChildren
  '/client/progress-pictures': typeof ClientProgressPicturesRouteWithChildren
  '/client/workout-history': typeof ClientWorkoutHistoryRoute
  '/coach/access-codes': typeof CoachAccessCodesRoute
  '/coach/chat': typeof CoachChatRouteWithChildren
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/library': typeof CoachLibraryRouteWithChildren
  '/coach/programs': typeof CoachProgramsRouteWithChildren
  '/payment/dashboard': typeof PaymentDashboardRoute
  '/payment/payouts': typeof PaymentPayoutsRoute
  '/client/progress-pictures/$batchId': typeof ClientProgressPicturesBatchIdRoute
  '/coach/chat/$clientId': typeof CoachChatClientIdRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
  '/coach/library/exercises': typeof CoachLibraryExercisesRoute
  '/coach/library/workouts': typeof CoachLibraryWorkoutsRouteWithChildren
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/client/program/': typeof ClientProgramIndexRoute
  '/client/progress-pictures/': typeof ClientProgressPicturesIndexRoute
  '/coach/chat/': typeof CoachChatIndexRoute
  '/coach/library/': typeof CoachLibraryIndexRoute
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/client/program/workouts/$workoutId': typeof ClientProgramWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId': typeof CoachLibraryWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/': typeof CoachLibraryWorkoutsIndexRoute
  '/coach/programs/$programId/': typeof CoachProgramsProgramIdIndexRoute
  '/client/programs/$programId/workouts/$workoutId': typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId/preview': typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/$workoutId/': typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId/': typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/client': typeof ClientRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRouteWithChildren
  '/client/chat': typeof ClientChatRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/workout-history': typeof ClientWorkoutHistoryRoute
  '/coach/access-codes': typeof CoachAccessCodesRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/payment/dashboard': typeof PaymentDashboardRoute
  '/payment/payouts': typeof PaymentPayoutsRoute
  '/client/progress-pictures/$batchId': typeof ClientProgressPicturesBatchIdRoute
  '/coach/chat/$clientId': typeof CoachChatClientIdRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
  '/coach/library/exercises': typeof CoachLibraryExercisesRoute
  '/client/program': typeof ClientProgramIndexRoute
  '/client/progress-pictures': typeof ClientProgressPicturesIndexRoute
  '/coach/chat': typeof CoachChatIndexRoute
  '/coach/library': typeof CoachLibraryIndexRoute
  '/coach/programs': typeof CoachProgramsIndexRoute
  '/client/program/workouts/$workoutId': typeof ClientProgramWorkoutsWorkoutIdRoute
  '/coach/library/workouts': typeof CoachLibraryWorkoutsIndexRoute
  '/coach/programs/$programId': typeof CoachProgramsProgramIdIndexRoute
  '/client/programs/$programId/workouts/$workoutId': typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId/preview': typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  '/coach/library/workouts/$workoutId': typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/client': typeof ClientRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRouteWithChildren
  '/client/chat': typeof ClientChatRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/program': typeof ClientProgramRouteWithChildren
  '/client/progress-pictures': typeof ClientProgressPicturesRouteWithChildren
  '/client/workout-history': typeof ClientWorkoutHistoryRoute
  '/coach/access-codes': typeof CoachAccessCodesRoute
  '/coach/chat': typeof CoachChatRouteWithChildren
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/library': typeof CoachLibraryRouteWithChildren
  '/coach/programs': typeof CoachProgramsRouteWithChildren
  '/payment/dashboard': typeof PaymentDashboardRoute
  '/payment/payouts': typeof PaymentPayoutsRoute
  '/client/progress-pictures/$batchId': typeof ClientProgressPicturesBatchIdRoute
  '/coach/chat/$clientId': typeof CoachChatClientIdRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
  '/coach/library/exercises': typeof CoachLibraryExercisesRoute
  '/coach/library/workouts': typeof CoachLibraryWorkoutsRouteWithChildren
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/client/program/': typeof ClientProgramIndexRoute
  '/client/progress-pictures/': typeof ClientProgressPicturesIndexRoute
  '/coach/chat/': typeof CoachChatIndexRoute
  '/coach/library/': typeof CoachLibraryIndexRoute
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/client/program/workouts/$workoutId': typeof ClientProgramWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId': typeof CoachLibraryWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/': typeof CoachLibraryWorkoutsIndexRoute
  '/coach/programs/$programId/': typeof CoachProgramsProgramIdIndexRoute
  '/client/programs/$programId/workouts/$workoutId': typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId/preview': typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/$workoutId/': typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId/': typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/client'
    | '/coach'
    | '/onboarding'
    | '/payment'
    | '/client/chat'
    | '/client/dashboard'
    | '/client/program'
    | '/client/progress-pictures'
    | '/client/workout-history'
    | '/coach/access-codes'
    | '/coach/chat'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/library'
    | '/coach/programs'
    | '/payment/dashboard'
    | '/payment/payouts'
    | '/client/progress-pictures/$batchId'
    | '/coach/chat/$clientId'
    | '/coach/clients/$clientId'
    | '/coach/library/exercises'
    | '/coach/library/workouts'
    | '/coach/programs/$programId'
    | '/client/program/'
    | '/client/progress-pictures/'
    | '/coach/chat/'
    | '/coach/library/'
    | '/coach/programs/'
    | '/client/program/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId'
    | '/coach/library/workouts/'
    | '/coach/programs/$programId/'
    | '/client/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/client'
    | '/coach'
    | '/onboarding'
    | '/payment'
    | '/client/chat'
    | '/client/dashboard'
    | '/client/workout-history'
    | '/coach/access-codes'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/payment/dashboard'
    | '/payment/payouts'
    | '/client/progress-pictures/$batchId'
    | '/coach/chat/$clientId'
    | '/coach/clients/$clientId'
    | '/coach/library/exercises'
    | '/client/program'
    | '/client/progress-pictures'
    | '/coach/chat'
    | '/coach/library'
    | '/coach/programs'
    | '/client/program/workouts/$workoutId'
    | '/coach/library/workouts'
    | '/coach/programs/$programId'
    | '/client/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/preview'
    | '/coach/library/workouts/$workoutId'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/client'
    | '/coach'
    | '/onboarding'
    | '/payment'
    | '/client/chat'
    | '/client/dashboard'
    | '/client/program'
    | '/client/progress-pictures'
    | '/client/workout-history'
    | '/coach/access-codes'
    | '/coach/chat'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/library'
    | '/coach/programs'
    | '/payment/dashboard'
    | '/payment/payouts'
    | '/client/progress-pictures/$batchId'
    | '/coach/chat/$clientId'
    | '/coach/clients/$clientId'
    | '/coach/library/exercises'
    | '/coach/library/workouts'
    | '/coach/programs/$programId'
    | '/client/program/'
    | '/client/progress-pictures/'
    | '/coach/chat/'
    | '/coach/library/'
    | '/coach/programs/'
    | '/client/program/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId'
    | '/coach/library/workouts/'
    | '/coach/programs/$programId/'
    | '/client/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ClientRoute: typeof ClientRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PaymentRoute: typeof PaymentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/payouts': {
      id: '/payment/payouts'
      path: '/payouts'
      fullPath: '/payment/payouts'
      preLoaderRoute: typeof PaymentPayoutsRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/payment/dashboard': {
      id: '/payment/dashboard'
      path: '/dashboard'
      fullPath: '/payment/dashboard'
      preLoaderRoute: typeof PaymentDashboardRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/coach/programs': {
      id: '/coach/programs'
      path: '/programs'
      fullPath: '/coach/programs'
      preLoaderRoute: typeof CoachProgramsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/library': {
      id: '/coach/library'
      path: '/library'
      fullPath: '/coach/library'
      preLoaderRoute: typeof CoachLibraryRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/dashboard': {
      id: '/coach/dashboard'
      path: '/dashboard'
      fullPath: '/coach/dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/chat': {
      id: '/coach/chat'
      path: '/chat'
      fullPath: '/coach/chat'
      preLoaderRoute: typeof CoachChatRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/access-codes': {
      id: '/coach/access-codes'
      path: '/access-codes'
      fullPath: '/coach/access-codes'
      preLoaderRoute: typeof CoachAccessCodesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/client/workout-history': {
      id: '/client/workout-history'
      path: '/workout-history'
      fullPath: '/client/workout-history'
      preLoaderRoute: typeof ClientWorkoutHistoryRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/progress-pictures': {
      id: '/client/progress-pictures'
      path: '/progress-pictures'
      fullPath: '/client/progress-pictures'
      preLoaderRoute: typeof ClientProgressPicturesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/program': {
      id: '/client/program'
      path: '/program'
      fullPath: '/client/program'
      preLoaderRoute: typeof ClientProgramRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/chat': {
      id: '/client/chat'
      path: '/chat'
      fullPath: '/client/chat'
      preLoaderRoute: typeof ClientChatRouteImport
      parentRoute: typeof ClientRoute
    }
    '/coach/programs/': {
      id: '/coach/programs/'
      path: '/'
      fullPath: '/coach/programs/'
      preLoaderRoute: typeof CoachProgramsIndexRouteImport
      parentRoute: typeof CoachProgramsRoute
    }
    '/coach/library/': {
      id: '/coach/library/'
      path: '/'
      fullPath: '/coach/library/'
      preLoaderRoute: typeof CoachLibraryIndexRouteImport
      parentRoute: typeof CoachLibraryRoute
    }
    '/coach/chat/': {
      id: '/coach/chat/'
      path: '/'
      fullPath: '/coach/chat/'
      preLoaderRoute: typeof CoachChatIndexRouteImport
      parentRoute: typeof CoachChatRoute
    }
    '/client/progress-pictures/': {
      id: '/client/progress-pictures/'
      path: '/'
      fullPath: '/client/progress-pictures/'
      preLoaderRoute: typeof ClientProgressPicturesIndexRouteImport
      parentRoute: typeof ClientProgressPicturesRoute
    }
    '/client/program/': {
      id: '/client/program/'
      path: '/'
      fullPath: '/client/program/'
      preLoaderRoute: typeof ClientProgramIndexRouteImport
      parentRoute: typeof ClientProgramRoute
    }
    '/coach/programs/$programId': {
      id: '/coach/programs/$programId'
      path: '/$programId'
      fullPath: '/coach/programs/$programId'
      preLoaderRoute: typeof CoachProgramsProgramIdRouteImport
      parentRoute: typeof CoachProgramsRoute
    }
    '/coach/library/workouts': {
      id: '/coach/library/workouts'
      path: '/workouts'
      fullPath: '/coach/library/workouts'
      preLoaderRoute: typeof CoachLibraryWorkoutsRouteImport
      parentRoute: typeof CoachLibraryRoute
    }
    '/coach/library/exercises': {
      id: '/coach/library/exercises'
      path: '/exercises'
      fullPath: '/coach/library/exercises'
      preLoaderRoute: typeof CoachLibraryExercisesRouteImport
      parentRoute: typeof CoachLibraryRoute
    }
    '/coach/clients/$clientId': {
      id: '/coach/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/coach/clients/$clientId'
      preLoaderRoute: typeof CoachClientsClientIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/chat/$clientId': {
      id: '/coach/chat/$clientId'
      path: '/$clientId'
      fullPath: '/coach/chat/$clientId'
      preLoaderRoute: typeof CoachChatClientIdRouteImport
      parentRoute: typeof CoachChatRoute
    }
    '/client/progress-pictures/$batchId': {
      id: '/client/progress-pictures/$batchId'
      path: '/$batchId'
      fullPath: '/client/progress-pictures/$batchId'
      preLoaderRoute: typeof ClientProgressPicturesBatchIdRouteImport
      parentRoute: typeof ClientProgressPicturesRoute
    }
    '/coach/programs/$programId/': {
      id: '/coach/programs/$programId/'
      path: '/'
      fullPath: '/coach/programs/$programId/'
      preLoaderRoute: typeof CoachProgramsProgramIdIndexRouteImport
      parentRoute: typeof CoachProgramsProgramIdRoute
    }
    '/coach/library/workouts/': {
      id: '/coach/library/workouts/'
      path: '/'
      fullPath: '/coach/library/workouts/'
      preLoaderRoute: typeof CoachLibraryWorkoutsIndexRouteImport
      parentRoute: typeof CoachLibraryWorkoutsRoute
    }
    '/coach/library/workouts/$workoutId': {
      id: '/coach/library/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/coach/library/workouts/$workoutId'
      preLoaderRoute: typeof CoachLibraryWorkoutsWorkoutIdRouteImport
      parentRoute: typeof CoachLibraryWorkoutsRoute
    }
    '/client/program/workouts/$workoutId': {
      id: '/client/program/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/client/program/workouts/$workoutId'
      preLoaderRoute: typeof ClientProgramWorkoutsWorkoutIdRouteImport
      parentRoute: typeof ClientProgramRoute
    }
    '/coach/library/workouts/$workoutId/': {
      id: '/coach/library/workouts/$workoutId/'
      path: '/'
      fullPath: '/coach/library/workouts/$workoutId/'
      preLoaderRoute: typeof CoachLibraryWorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof CoachLibraryWorkoutsWorkoutIdRoute
    }
    '/coach/programs/$programId/workouts/$workoutId': {
      id: '/coach/programs/$programId/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/coach/programs/$programId/workouts/$workoutId'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport
      parentRoute: typeof CoachProgramsProgramIdRoute
    }
    '/coach/library/workouts/$workoutId/preview': {
      id: '/coach/library/workouts/$workoutId/preview'
      path: '/preview'
      fullPath: '/coach/library/workouts/$workoutId/preview'
      preLoaderRoute: typeof CoachLibraryWorkoutsWorkoutIdPreviewRouteImport
      parentRoute: typeof CoachLibraryWorkoutsWorkoutIdRoute
    }
    '/client/programs/$programId/workouts/$workoutId': {
      id: '/client/programs/$programId/workouts/$workoutId'
      path: '/programs/$programId/workouts/$workoutId'
      fullPath: '/client/programs/$programId/workouts/$workoutId'
      preLoaderRoute: typeof ClientProgramsProgramIdWorkoutsWorkoutIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/coach/programs/$programId/workouts/$workoutId/': {
      id: '/coach/programs/$programId/workouts/$workoutId/'
      path: '/'
      fullPath: '/coach/programs/$programId/workouts/$workoutId/'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRoute
    }
    '/coach/programs/$programId/workouts/$workoutId/preview': {
      id: '/coach/programs/$programId/workouts/$workoutId/preview'
      path: '/preview'
      fullPath: '/coach/programs/$programId/workouts/$workoutId/preview'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport
      parentRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRoute
    }
  }
}

interface ClientProgramRouteChildren {
  ClientProgramIndexRoute: typeof ClientProgramIndexRoute
  ClientProgramWorkoutsWorkoutIdRoute: typeof ClientProgramWorkoutsWorkoutIdRoute
}

const ClientProgramRouteChildren: ClientProgramRouteChildren = {
  ClientProgramIndexRoute: ClientProgramIndexRoute,
  ClientProgramWorkoutsWorkoutIdRoute: ClientProgramWorkoutsWorkoutIdRoute,
}

const ClientProgramRouteWithChildren = ClientProgramRoute._addFileChildren(
  ClientProgramRouteChildren,
)

interface ClientProgressPicturesRouteChildren {
  ClientProgressPicturesBatchIdRoute: typeof ClientProgressPicturesBatchIdRoute
  ClientProgressPicturesIndexRoute: typeof ClientProgressPicturesIndexRoute
}

const ClientProgressPicturesRouteChildren: ClientProgressPicturesRouteChildren =
  {
    ClientProgressPicturesBatchIdRoute: ClientProgressPicturesBatchIdRoute,
    ClientProgressPicturesIndexRoute: ClientProgressPicturesIndexRoute,
  }

const ClientProgressPicturesRouteWithChildren =
  ClientProgressPicturesRoute._addFileChildren(
    ClientProgressPicturesRouteChildren,
  )

interface ClientRouteChildren {
  ClientChatRoute: typeof ClientChatRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientProgramRoute: typeof ClientProgramRouteWithChildren
  ClientProgressPicturesRoute: typeof ClientProgressPicturesRouteWithChildren
  ClientWorkoutHistoryRoute: typeof ClientWorkoutHistoryRoute
  ClientProgramsProgramIdWorkoutsWorkoutIdRoute: typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientChatRoute: ClientChatRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientProgramRoute: ClientProgramRouteWithChildren,
  ClientProgressPicturesRoute: ClientProgressPicturesRouteWithChildren,
  ClientWorkoutHistoryRoute: ClientWorkoutHistoryRoute,
  ClientProgramsProgramIdWorkoutsWorkoutIdRoute:
    ClientProgramsProgramIdWorkoutsWorkoutIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface CoachChatRouteChildren {
  CoachChatClientIdRoute: typeof CoachChatClientIdRoute
  CoachChatIndexRoute: typeof CoachChatIndexRoute
}

const CoachChatRouteChildren: CoachChatRouteChildren = {
  CoachChatClientIdRoute: CoachChatClientIdRoute,
  CoachChatIndexRoute: CoachChatIndexRoute,
}

const CoachChatRouteWithChildren = CoachChatRoute._addFileChildren(
  CoachChatRouteChildren,
)

interface CoachLibraryWorkoutsWorkoutIdRouteChildren {
  CoachLibraryWorkoutsWorkoutIdPreviewRoute: typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  CoachLibraryWorkoutsWorkoutIdIndexRoute: typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
}

const CoachLibraryWorkoutsWorkoutIdRouteChildren: CoachLibraryWorkoutsWorkoutIdRouteChildren =
  {
    CoachLibraryWorkoutsWorkoutIdPreviewRoute:
      CoachLibraryWorkoutsWorkoutIdPreviewRoute,
    CoachLibraryWorkoutsWorkoutIdIndexRoute:
      CoachLibraryWorkoutsWorkoutIdIndexRoute,
  }

const CoachLibraryWorkoutsWorkoutIdRouteWithChildren =
  CoachLibraryWorkoutsWorkoutIdRoute._addFileChildren(
    CoachLibraryWorkoutsWorkoutIdRouteChildren,
  )

interface CoachLibraryWorkoutsRouteChildren {
  CoachLibraryWorkoutsWorkoutIdRoute: typeof CoachLibraryWorkoutsWorkoutIdRouteWithChildren
  CoachLibraryWorkoutsIndexRoute: typeof CoachLibraryWorkoutsIndexRoute
}

const CoachLibraryWorkoutsRouteChildren: CoachLibraryWorkoutsRouteChildren = {
  CoachLibraryWorkoutsWorkoutIdRoute:
    CoachLibraryWorkoutsWorkoutIdRouteWithChildren,
  CoachLibraryWorkoutsIndexRoute: CoachLibraryWorkoutsIndexRoute,
}

const CoachLibraryWorkoutsRouteWithChildren =
  CoachLibraryWorkoutsRoute._addFileChildren(CoachLibraryWorkoutsRouteChildren)

interface CoachLibraryRouteChildren {
  CoachLibraryExercisesRoute: typeof CoachLibraryExercisesRoute
  CoachLibraryWorkoutsRoute: typeof CoachLibraryWorkoutsRouteWithChildren
  CoachLibraryIndexRoute: typeof CoachLibraryIndexRoute
}

const CoachLibraryRouteChildren: CoachLibraryRouteChildren = {
  CoachLibraryExercisesRoute: CoachLibraryExercisesRoute,
  CoachLibraryWorkoutsRoute: CoachLibraryWorkoutsRouteWithChildren,
  CoachLibraryIndexRoute: CoachLibraryIndexRoute,
}

const CoachLibraryRouteWithChildren = CoachLibraryRoute._addFileChildren(
  CoachLibraryRouteChildren,
)

interface CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren {
  CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}

const CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren: CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren =
  {
    CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute,
    CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute,
  }

const CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren =
  CoachProgramsProgramIdWorkoutsWorkoutIdRoute._addFileChildren(
    CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren,
  )

interface CoachProgramsProgramIdRouteChildren {
  CoachProgramsProgramIdIndexRoute: typeof CoachProgramsProgramIdIndexRoute
  CoachProgramsProgramIdWorkoutsWorkoutIdRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
}

const CoachProgramsProgramIdRouteChildren: CoachProgramsProgramIdRouteChildren =
  {
    CoachProgramsProgramIdIndexRoute: CoachProgramsProgramIdIndexRoute,
    CoachProgramsProgramIdWorkoutsWorkoutIdRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren,
  }

const CoachProgramsProgramIdRouteWithChildren =
  CoachProgramsProgramIdRoute._addFileChildren(
    CoachProgramsProgramIdRouteChildren,
  )

interface CoachProgramsRouteChildren {
  CoachProgramsProgramIdRoute: typeof CoachProgramsProgramIdRouteWithChildren
  CoachProgramsIndexRoute: typeof CoachProgramsIndexRoute
}

const CoachProgramsRouteChildren: CoachProgramsRouteChildren = {
  CoachProgramsProgramIdRoute: CoachProgramsProgramIdRouteWithChildren,
  CoachProgramsIndexRoute: CoachProgramsIndexRoute,
}

const CoachProgramsRouteWithChildren = CoachProgramsRoute._addFileChildren(
  CoachProgramsRouteChildren,
)

interface CoachRouteChildren {
  CoachAccessCodesRoute: typeof CoachAccessCodesRoute
  CoachChatRoute: typeof CoachChatRouteWithChildren
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachLibraryRoute: typeof CoachLibraryRouteWithChildren
  CoachProgramsRoute: typeof CoachProgramsRouteWithChildren
  CoachClientsClientIdRoute: typeof CoachClientsClientIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachAccessCodesRoute: CoachAccessCodesRoute,
  CoachChatRoute: CoachChatRouteWithChildren,
  CoachDashboardRoute: CoachDashboardRoute,
  CoachExercisesRoute: CoachExercisesRoute,
  CoachLibraryRoute: CoachLibraryRouteWithChildren,
  CoachProgramsRoute: CoachProgramsRouteWithChildren,
  CoachClientsClientIdRoute: CoachClientsClientIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface PaymentRouteChildren {
  PaymentDashboardRoute: typeof PaymentDashboardRoute
  PaymentPayoutsRoute: typeof PaymentPayoutsRoute
}

const PaymentRouteChildren: PaymentRouteChildren = {
  PaymentDashboardRoute: PaymentDashboardRoute,
  PaymentPayoutsRoute: PaymentPayoutsRoute,
}

const PaymentRouteWithChildren =
  PaymentRoute._addFileChildren(PaymentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ClientRoute: ClientRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PaymentRoute: PaymentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
