// Cloud configuration helper. The Supabase client itself is generated by
// Lovable (src/integrations/supabase/client.ts) — this file is ours.
export function isSupabaseConfigured(): boolean {
  const url =
    typeof import.meta !== "undefined" && import.meta.env
      ? (import.meta.env.VITE_SUPABASE_URL as string | undefined)
      : undefined;
  const key =
    typeof import.meta !== "undefined" && import.meta.env
      ? (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
        (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)
      : undefined;
  return Boolean(url && key);
}
